void availability();
void booking();
int search(char *str, int studentID);
void reallocation();
void roomdetails();
void maleroom();
void femaleroom();
void store(char *str, int i, struct hostelers block2);
int roomnumber(int line, int i);
void mainmenu();
int countingBeds(char *str);
void deleting(char *str, int j);
void cancel();
int countingzero(char *str);
void searchempty(char *str);
int bedavail(char *str);
int billing(int weeks, char *str, int service);
void payment();
void amountreceivable();
void goback();